name: First Workflow

on: push

jobs:
    firstJob:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Greeting
              run: echo "Hello!!!"
            - name: OS Name
              run: uname -a
            - name: Disk Free
              run: df -h
